site_name:           COBRA.jl
repo_url:            https://github.com/opencobra/COBRA.jl
site_description:    Julia package for COBRA - COnstraint-Based Reconstruction and Analysis
site_author:         Dr. Laurent Heirendt et al.
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  #- mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Beginner's Guide: cbg.md
- Tutorial: cobratutorial.md
- Configuration: configuration.md
- Modules and Functions: functions.md
- FAQ: faq.md
- Index: contents.md
